name: narratives-detection
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.11
- pandas
- matplotlib
- jupyter
- Flask
- python-dotenv
- pip
- requests
- psycopg2

- pip:
  - spacy 
  - wikipedia
  - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.0/en_core_web_sm-3.7.0.tar.gz